sudo: false
language: node_js
node_js:
  - v14
  - v12
  - v10
branches:
  only:
  - master
before_script:
  # Extract the deploy key from secure variables for deploying the website
  - 'echo -n $id_rsa_{00..60} >> ~/.ssh/id_rsa_base64'
  - 'base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa'
  - 'chmod 600 ~/.ssh/id_rsa'
  - 'echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
  - 'git config --global user.email "info@kollavarsham.org"'
  - 'git config --global user.name "The Kollavarsham Team"'
  # Install the dependencies
  - 'npm install -g bower@1.8.4 grunt-cli istanbul'
  - 'bower install'
after_success:
  # Push code coverage & deploy the web app
  - 'if [ "$TRAVIS_NODE_VERSION" = "v10" ]; then grunt deploy; fi'
